

<h1> General rubric </h1>
<hr>

<h3>Attendence policy</h3>
<ul>

<li>Tardy arrival at class by more than 40 minutes will constitute an unexcused absence which means 10 pts lost(plus loss of credit for missed work).
</li>

<li>Tardy arrival by less than 20 minutes will be automatically excused on the first occasion.
</li>

<li>Tardy arrival by less than 20 minutes on the second and subsequent occasions will constitute an unexcused absence which means 10 pts lost.
</li>

</ul>

<table border="1">
<tr>
<td> </td>
<td> points</td>
<td> time</td>
<td> total pts</td>
</tr>

<tr>
<td>prelim reports  </td>
<td> 10</td>
<td> 8 </td>
<td> 80 </td>
</tr>

<tr>
<td>lab reports  </td>
<td> 30</td>
<td> 8 </td>
<td> 240 </td>
</tr>


<tr>
<td> critiques </td>
<td> 2 </td>
<td> 4 </td>
<td> 8 </td>
</tr>

<tr>
<td> oral prensentation </td>
<td> 50</td>
<td> 1 </td>
<td> 50</td>
</tr>

<tr>
<td> class participation </td>
<td> ## </td>
<td>  13</td>
<td> 22 </td>
</tr>

<tr>
<td> </td>
<td> </td>
<td> </td>
<td> 400</td>
</tr>

</table>


<h3> About prelim report </h3>
You don't have to write anything for prelim report,just print out the "project description"(you can download from <a href=" http://www.physics.sc.edu/~physlab/uplp.html">here </a>), read and get familiar with the procejures, and bring your "project description" to class. If in class I don't see project description at your hand, then you lose -5 pts, if you are found having not read the paper, also 5 pts lost.( So if you rush into the lab and tell me you couldn't find a printer this morning, you still have 5 pts lost even though I will let you print by the lab printer) You can't bring a laptop and say you already downloaded the file and read it without printint it out, but you can use a tablet instead of printint it.

<h3> About lab report </h3>
For final lab report, after you did the experiment, you need to turn in your lab report before next time,namely 7 days. Some of you may be afraid of getting a bad score of your lab report, but I'll give you a chance to amend if you turn in it at least one day before the deadline. However, your score can only get changed if you can amend it and turn in it again by same deadline. So, I strongly suggest you to turn in lab report asap, so if you are not satisfied with your score, you have enough time to go to my office to ask how to correct it, then go back home, correct, turn in again.
If you want to know how I grade your lab report, go to <a href="reportrubric.php"> my special grading rubric</a>.


<h3> About class participation </h3>
There are 22 points for class participation. Some people like to form a big group like 4 or more than that, but in this case, very few of you will master the skill of doing the experiment. So you need to form group two by two first, If there are not enough apparatus, then the ungrouped people can join each formed group one by one. But the normal situation is that we have 20 people around for any lab section, and we have 5 equipments for both each time's project A and project B, so in your lab section, there are less than 20 people, then you can only 2 people's group. In the beginning period of our lab, you may don't know this regulation, so I will tell you to form a group two by two after I find you didn't do as that, but after that, you still don't obey the regulation, 10 pts may get lost for each member of your group.






