
<div id="lab_main">



<p> 202sec6(Tue6:45)  202secH01(Th6:45)  212sec7(Mon 5:50) </p>

<h3> <a href="grubric.php"> General Rubric</a> </h3>


<h3><a href="reportrubric.php"> Lab report grading rubric </a></h3>


useful links: 
<ul>
   <li> How to write a <a href="http://www.physics.sc.edu/~physlab/writtenReportHowTo.html"> Final Project Report. </a> 


</li>
   <li> How to prepare an <a href="http://www.physics.sc.edu/~physlab/oralPresHowTo.html"> Oral Presentation.</a> </li>
</ul>

<br>

Tips for each experiment and lab report:






<table border="1">

<tr>
<td rowspan="2"> Cycle 1    </td>
   <td>  Equipotentials  </td>
   <td>  Experiment </td>
   <td>  Lab Report   </td>
  <tr> 
    <td> Ohm's Law   </td> 
    <td>  Experiment </td>
   <td>  <a href="tips/report/ohm.html"> Lab Report  </a> </td>
  </tr>
</tr>

<tr>
<td rowspan="2"> Cycle 2    </td>
   <td>  Series and Parallel Resistance </td>
   <td>  Experiment </td>
   <td>  Lab Report   </td>
  <tr> 
    <td> Current Balance  </td> 
    <td>  Experiment </td>
   <td>  Lab Report   </td>
  </tr>
</tr>


<tr>
<td rowspan="3"> Cycle 3    </td>
   <td> Double Slit Diffraction </td>
   <td>  Experiment </td>
   <td>  Lab Report   </td>
  <tr> 
    <td> Geometric optics  </td> 
    <td>  Experiment </td>
   <td>  Lab Report   </td>
  </tr>
   <tr> 
    <td> Balmer Series </td> 
    <td>  Experiment </td>
   <td>  Lab Report   </td>
  </tr>
</tr>

<tr>
<td rowspan="3"> Cycle 4    </td>
   <td>  CD Diffration </td>
   <td>  Experiment </td>
   <td>  Lab Report   </td>
  <tr> 
    <td>Optics of the Eye </td> 
    <td>  Experiment </td>
   <td>  Lab Report   </td>
  </tr>
   <tr> 
    <td>Photoelectric Effect</td> 
    <td>  Experiment </td>
   <td>  Lab Report   </td>
  </tr>
</tr>

</table>

<br>
Physics skills dictionary:
<br>
<a href="diction/d1_multi.php"> How to use a multimeter to measure current and voltage?</a>
<br>

How to do error analysis?  


    


</div>
