
<h1>LAB REPORT GRADING RUBRIC </h1>
<hr>

<p style="color:red;"> Attention: this lab report special grading rubric is just an additional rubric of the official one(<a href="http://www.physics.sc.edu/~physlab/writtenReportHowTo.html"> see here </a>).
</p>


<ul>
<li>
There are 8 sections for a complete physics lab report,see details in table 1 below.
</li>
<br>
<li>
In physics, numbers are always followed by units or it will lose meaning, never forget this! You need write units in all the calculations, tables, graphs(x,y coordinates) etc.
</li>
<br>
</ul>

<table border="1" >
<caption> Table 1 </caption>
<tr>
<th> Order</th>
<th> Section</th>
<th> Requirements</th>
</tr>

<tr>
<td>1</td>
<td> Abstract</td>
<td>
<ul class="a">
<li>as brief as possible</li>
<li>written at the bottom of the first page.</li>
</ul>


 </td>

</tr>

<tr>
<td> 2</td>
<td>Background </td>
<td> 
<ul class="a">
<li> as brief as possible</li>
<li> written from the second page. </li>
</ul>

</td>
</tr>

<tr>
<td> 3</td>
<td>Procedure </td>
<td> 
<ul class="a">
<li> as brief as possible </li>
<li> you can just show a picture without writing any words. </li>
</td>
</tr>

<tr>
<td> 4</td>
<td> Results/Analysis/Physics</td>
<td> includes all the tables(with units),graphs(with units),diagrams, error analyses, etc.</td>
</tr>

<tr>
<td> 5</td>
<td> Calculation Page</td>
<td> Don't forget units!</td>
</tr>

<tr>
<td> 6</td>
<td> Questions</td>
<td> 

write the question down before answer it, number each question.

</td>
</tr>

<tr>
<td>7 </td>
<td>Conclusion </td>
<td> Two paragraphs are enough
<ol>
<li> one for summery </li>
<li>  Another for making connections between your findings and the world outside the lab</li>
</ol>





</td>
</tr>

<tr>
<td>8</td>
<td>References </td>
<td> </td>
</tr>

</table>



<table border="1" cellpadding="3px" >
<caption> Table 2( how are your points lost) </caption>

<tr>
<td>  </td>
<td>  </td>
<th> Example </th>
</tr>

<tr bgcolor="aqua">
<td> wrong format </td>
<td>  -1 for each </td>
<td> 
<ul>

<li> ABSTRACT on second page</li> 
<li> ABSTRACT not at the bottom of the first page</li> 
<li> BACKGROUND on first page</li> 
<li> no references</li> 
</ul>

</td>
</tr>




<tr bgcolor="aqua">
<td> units omission </td>
<td> -3 </td>
<td> no units in the table or in your calculation or in the x,y coordinates of your graphs </td>
</tr>

<tr bgcolor="yellow">
<td> graph no trendline  <br> (if needed)
 </td>
<td>  -2 </td>
<td>  </td>
</tr>

<tr bgcolor="yellow">
<td> graph wrong trendline </td>
<td> -1 for each </td>
<td>  </td>
</tr>

<tr bgcolor="yellow">
<td> graph x,y coordinates wrong choosing </td>
<td> -2 for each</td>
<td>  </td>
</tr>

<tr bgcolor="aqua">
<td> no questions, no sequence numbers</td>
<td> -3</td>
<td> Before you answer questions, you need to write down the question first. </td>
</tr>

<tr bgcolor="aqua">
<td> wrong answer to the question </td>
<td> -1 for each </td>
<td>  </td>
</tr>

<tr bgcolor="yellow">
<td> no calculation procedure <br>
(if needed)
 </td>
<td> -2 for each step </td>
<td>  </td>
</tr>

<tr bgcolor="yellow">
<td> wrong calculation </td>
<td>  -1 for each step </td>
<td>  </td>
</tr>

<tr bgcolor="yellow">
<td> no error analysis 
<br> (if needed)
</td>
<td> -1 for each </td>
<td>  </td>
</tr>

<tr bgcolor="aqua">
<td> lack of logic and neatness </td>
<td> -1 to -5 </td>
<td>  </td>
</tr>


</table>