

<h3> how to use a multimeter:</h3>
<hr>
<ol>
<li>
 In our lab always turn dial to DC rather than AC no matter current or voltage is to be measured.( In one of our two types of multimeters, a yellow button is used for switching between AC and DC)
</li>
<li>
 Always plug the black test lead to the "COM" jack, plug the red test lead to the "A" jack if measure current, to the "V" jack if measure voltage.
</li>
</ol>

<i> want to know more? see <a href="multimeteruse.pdf" >this</a>.</i>